# Generated by Django 5.0.4 on 2024-05-09 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.ImageField(max_length=15, upload_to='')),
                ('college', models.CharField(max_length=225)),
                ('degree', models.CharField(max_length=220)),
                ('address', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.courses')),
            ],
        ),
    ]
