# Generated by Django 5.0.4 on 2024-05-09 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
