# Generated by Django 5.0.4 on 2024-05-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
