# Generated by Django 5.0.4 on 2024-05-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='USer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
